begin;

insert into champion_name values (1, 'Annie');
insert into champion_name values (2, 'Olaf');
insert into champion_name values (3, 'Galio');
insert into champion_name values (4, 'Twisted Fate');
insert into champion_name values (5, 'Xin Zhao');
insert into champion_name values (6, 'Urgot');
insert into champion_name values (7, 'LeBlanc');
insert into champion_name values (8, 'Vladimir');
insert into champion_name values (9, 'Fiddlesticks');
insert into champion_name values (10, 'Kayle');
insert into champion_name values (11, 'Master Yi');
insert into champion_name values (12, 'Alistar');
insert into champion_name values (13, 'Ryze');
insert into champion_name values (14, 'Sion');
insert into champion_name values (15, 'Sivir');
insert into champion_name values (16, 'Soraka');
insert into champion_name values (17, 'Teemo');
insert into champion_name values (18, 'Tristana');
insert into champion_name values (19, 'Warwick');
insert into champion_name values (20, 'Nunu');
insert into champion_name values (21, 'Miss Fortune');
insert into champion_name values (22, 'Ashe');
insert into champion_name values (23, 'Tryndamere');
insert into champion_name values (24, 'Jax');
insert into champion_name values (25, 'Morgana');
insert into champion_name values (26, 'Zilean');
insert into champion_name values (27, 'Singed');
insert into champion_name values (28, 'Evelynn');
insert into champion_name values (29, 'Twitch');
insert into champion_name values (30, 'Karthus');
insert into champion_name values (31, 'Cho''Gath');
insert into champion_name values (32, 'Amumu');
insert into champion_name values (33, 'Rammus');
insert into champion_name values (34, 'Anivia');
insert into champion_name values (35, 'Shaco');
insert into champion_name values (36, 'Dr. Mundo');
insert into champion_name values (37, 'Sona');
insert into champion_name values (38, 'Kassadin');
insert into champion_name values (39, 'Irelia');
insert into champion_name values (40, 'Janna');
insert into champion_name values (41, 'Gangplank');
insert into champion_name values (42, 'Corki');
insert into champion_name values (43, 'Karma');
insert into champion_name values (44, 'Taric');
insert into champion_name values (45, 'Veigar');
insert into champion_name values (48, 'Trundle');
insert into champion_name values (50, 'Swain');
insert into champion_name values (51, 'Caitlyn');
insert into champion_name values (53, 'Blitzcrank');
insert into champion_name values (54, 'Malphite');
insert into champion_name values (55, 'Katarina');
insert into champion_name values (56, 'Nocturne');
insert into champion_name values (57, 'Maokai');
insert into champion_name values (58, 'Renekton');
insert into champion_name values (59, 'Jarvan IV');
insert into champion_name values (61, 'Orianna');
insert into champion_name values (62, 'Wukong');
insert into champion_name values (63, 'Brand');
insert into champion_name values (64, 'Lee Sin');
insert into champion_name values (67, 'Vayne');
insert into champion_name values (68, 'Rumble');
insert into champion_name values (69, 'Cassiopeia');
insert into champion_name values (72, 'Skarner');
insert into champion_name values (74, 'Heimerdinger');
insert into champion_name values (75, 'Nasus');
insert into champion_name values (76, 'Nidalee');
insert into champion_name values (77, 'Udyr');
insert into champion_name values (78, 'Poppy');
insert into champion_name values (79, 'Gragas');
insert into champion_name values (80, 'Pantheon');
insert into champion_name values (81, 'Ezreal');
insert into champion_name values (82, 'Mordekaiser');
insert into champion_name values (83, 'Yorick');
insert into champion_name values (84, 'Akali');
insert into champion_name values (85, 'Kennen');
insert into champion_name values (86, 'Garen');
insert into champion_name values (89, 'Leona');
insert into champion_name values (90, 'Malzahar');
insert into champion_name values (91, 'Talon');
insert into champion_name values (92, 'Riven');
insert into champion_name values (96, 'Kog''Maw');
insert into champion_name values (98, 'Shen');
insert into champion_name values (99, 'Lux');
insert into champion_name values (101, 'Xerath');
insert into champion_name values (102, 'Shyvana');
insert into champion_name values (103, 'Ahri');
insert into champion_name values (104, 'Graves');
insert into champion_name values (105, 'Fizz');
insert into champion_name values (106, 'Volibear');
insert into champion_name values (111, 'Nautilus');
insert into champion_name values (112, 'Viktor');
insert into champion_name values (113, 'Sejuani');
insert into champion_name values (114, 'Fiora');
insert into champion_name values (115, 'Ziggs');

commit;