begin;

insert into item_information values (1001, 'Boots of Speed', 'UNIQUE Passive: Enhanced Movement 1 (does not stack with other Boots)');
insert into item_information values (1004, 'Faerie Charm', '+3 Mana Regen per 5 seconds');
insert into item_information values (1005, 'Meki Pendant', '+7 Mana Regen per 5 seconds');
insert into item_information values (1006, 'Rejuvenation Bead', '+8 Health Regen per 5 seconds');
insert into item_information values (1007, 'Regrowth Pendant', '+15 Health Regen per 5 seconds');
insert into item_information values (1011, 'Giant''s Belt', '+430 Health');
insert into item_information values (1018, 'Cloak of Agility', '+18% Critical Strike Chance');
insert into item_information values (1026, 'Blasting Wand', '+40 Ability Power');
insert into item_information values (1027, 'Sapphire Crystal', '+200 Mana');
insert into item_information values (1028, 'Ruby Crystal', '+180 Health');
insert into item_information values (1029, 'Cloth Armor', '+18 Armor');
insert into item_information values (1031, 'Chain Vest', '+45 Armor');
insert into item_information values (1033, 'Null-Magic Mantle', '+24 Magic Resist');
insert into item_information values (1036, 'Long Sword', '+10 Attack Damage');
insert into item_information values (1037, 'Pickaxe', '+25 Attack Damage');
insert into item_information values (1038, 'B. F. Sword', '+45 Attack Damage');
insert into item_information values (1042, 'Dagger', '+15% Attack Speed');
insert into item_information values (1043, 'Recurve Bow', '+40% Attack Speed');
insert into item_information values (1051, 'Brawler''s Gloves', '+8% Critical Strike Chance');
insert into item_information values (1052, 'Amplifying Tome', '+20 Ability Power');
insert into item_information values (1053, 'Vampiric Scepter', '+12% Life Steal');
insert into item_information values (1054, 'Doran''s Shield', '+120 Health +10 Armor +8 Health Regen per 5 seconds');
insert into item_information values (1055, 'Doran''s Blade', '+100 Health +10 Attack Damage +3% Life Steal');
insert into item_information values (1056, 'Doran''s Ring', '+100 Health +15 Ability Power +5 Mana Regen per 5 seconds');
insert into item_information values (1057, 'Negatron Cloak', '+48 Magic Resist');
insert into item_information values (1058, 'Needlessly Large Rod', '+80 Ability Power');
insert into item_information values (1062, 'Prospector''s Blade', '+20 Attack Damage +5% Life Steal  UNIQUE Passive: +200 Health (does not stack with other Prospector items)');
insert into item_information values (1063, 'Prospector''s Ring', '+30 Ability Power +7 Mana Regen per 5 seconds  UNIQUE Passive: +200 Health (does not stack with other Prospector items)');
insert into item_information values (2003, 'Health Potion', 'Click to Consume: Restores 150 Health over 15 seconds.');
insert into item_information values (2004, 'Mana Potion', 'Click to Consume: Restores 100 Mana over 15 seconds.');
insert into item_information values (2037, 'Elixir of Fortitude', 'Click to Consume: Grants 140-235 Health, based on champion level, and 10 Attack Damage for 4 minutes.');
insert into item_information values (2038, 'Elixir of Agility', 'Click to Consume: Grants 12-22% Attack Speed, based on champion level, and 8% Critical Strike Chance for 4 minutes.');
insert into item_information values (2039, 'Elixir of Brilliance', 'Click to Consume: Grants 20-40 Ability Power, based on champion level, and 10% Cooldown Reduction for 4 minutes.');
insert into item_information values (2042, 'Oracle''s Elixir', 'Click to Consume: Grants stealth detection until your champion dies.');
insert into item_information values (2043, 'Vision Ward', 'Click to Consume: Places an invisible ward that reveals the surrounding area and stealthed units in the area for 3 minutes.');
insert into item_information values (2044, 'Sight Ward', 'Click to Consume: Places an invisible ward that reveals the surrounding area for 3 minutes.');
insert into item_information values (2047, 'Oracle''s Extract', 'Click to Consume: Grants stealth detection for 5 minutes or until your champion dies.');
insert into item_information values (3001, 'Abyssal Scepter', '+70 Ability Power +57 Magic Resist  UNIQUE Aura: Reduces the Magic Resist of nearby enemy champions by 20.');
insert into item_information values (3003, 'Archangel''s Staff', '+400 Mana +25 Mana Regen per 5 seconds +45 Ability Power  Passive: Grants Ability Power equal to 3% of...');
insert into item_information values (3004, 'Manamune', '+350 Mana +7 Mana Regen per 5 seconds +20 Attack Damage  UNIQUE Passive: Grants Attack Damage equal to...');
insert into item_information values (3005, 'Atma''s Impaler', '+45 Armor +18% Critical Strike Chance  UNIQUE Passive: Gain Attack Damage equal to 2% of your maximum Health.');
insert into item_information values (3006, 'Berserker''s Greaves', ' +25% Attack Speed  UNIQUE Passive: Enhanced Movement 2 (does not stack with other Boots)');
insert into item_information values (3009, 'Boots of Swiftness', 'UNIQUE Passive: Enhanced Movement 3 (does not stack with other Boots)');
insert into item_information values (3010, 'Catalyst the Protector', '+290 Health +325 Mana  UNIQUE Passive: On leveling up, restores 250 Health and 200 Mana over 8 seconds.');
insert into item_information values (3020, 'Sorcerer''s Shoes', '+20 Magic Penetration  UNIQUE Passive: Enhanced Movement 2 (does not stack with other Boots)');
insert into item_information values (3022, 'Frozen Mallet', '+700 Health +20 Attack Damage  UNIQUE Passive: Your basic attacks slow your target''s Movement Speed by 40% for 2.5 seconds (30% for ranged attacks).');
insert into item_information values (3024, 'Glacial Shroud', '+425 Mana +45 Armor  UNIQUE Passive: +15% Cooldown Reduction');
insert into item_information values (3026, 'Guardian Angel', '+68 Armor +38 Magic Resist  UNIQUE Passive: Revives your champion upon death, restoring 750 Health and 375 Mana (5 minute cooldown).');
insert into item_information values (3027, 'Rod of Ages', '+450 Health +525 Mana +60 Ability Power  Passive: Your champion gains 18 Health, 20 Mana, and 2 Ability Power every minute (up to 10 times).  UNIQUE Passive: On leveling up, restores 250 Health and 200 Mana over 8 seconds.');
insert into item_information values (3028, 'Chalice of Harmony', '+30 Magic Resist +7.5 Mana Regen per 5 seconds  UNIQUE Passive: Increases your Mana Regen by 1% per 1% Mana you are missing.');
insert into item_information values (3031, 'Infinity Edge', '+80 Attack Damage +25% Critical Strike Chance  UNIQUE Passive: Your critical strikes now deal 250% damage instead of 200%.');
insert into item_information values (3035, 'Last Whisper', '+40 Attack Damage  UNIQUE Passive: +40% Armor Penetration');
insert into item_information values (3037, 'Mana Manipulator', 'UNIQUE Aura: Nearby allied champions gain 7.2 Mana Regen per 5 seconds.');
insert into item_information values (3041, 'Mejai''s Soulstealer', '+20 Ability Power  UNIQUE Passive: Your champion gains 8 Ability Power per stack, receiving 2 stacks...');
insert into item_information values (3044, 'Phage', '+225 Health +18 Attack Damage  UNIQUE Passive: Your basic attacks have a 25% chance to slow your target''s Movement Speed by 30% for 2.5 seconds.');
insert into item_information values (3046, 'Phantom Dancer', '+55% Attack Speed +30% Critical Strike Chance +15% Movement Speed');
insert into item_information values (3047, 'Ninja Tabi', '+25 Armor  UNIQUE Passive: Reduces the damage taken from non-turret basic attacks by 10%.  UNIQUE Passive: Enhanced Movement 2 (does not stack with other Boots)');
insert into item_information values (3050, 'Zeke''s Herald', '+250 Health UNIQUE Passive: +15% Cooldown Reduction UNIQUE Aura: Grants nearby allied champions 12% Life Steal and 20% Attack Speed.');
insert into item_information values (3057, 'Sheen', '+250 Mana +25 Ability Power  UNIQUE Passive: After using an ability, your next basic attack deals bonus physical damage equal to your base Attack Damage (2 second cooldown). Does not stack with Trinity Force or Lich Bane.');
insert into item_information values (3065, 'Spirit Visage', '+30 Magic Resist +250 Health  UNIQUE Passive: +10% Cooldown Reduction  UNIQUE Passive: Increases your healing and regeneration effects on yourself by 15%.');
insert into item_information values (3067, 'Kindlegem', '+200 Health  UNIQUE Passive: +10% Cooldown Reduction');
insert into item_information values (3068, 'Sunfire Cape', '+450 Health +45 Armor  UNIQUE Passive: Deals 35 magic damage per second to nearby enemies.');
insert into item_information values (3069, 'Shurelya''s Reverie', '+330 Health +30 Health Regen per 5 seconds +15 Mana Regen per 5 seconds  UNIQUE Passive: +15% Cooldown Reduction  UNIQUE Active: Nearby allied champions gain 40% Movement Speed for 3 seconds (60 second cooldown).');
insert into item_information values (3070, 'Tear of the Goddess', '+350 Mana +7 Mana Regen per 5 seconds  UNIQUE Passive: Each time you use an ability, your maximum Mana increases by 4 (3 second cooldown). Bonus caps at +1000 Mana. Does not stack with Archangel''s Staff or Manamune.');
insert into item_information values (3071, 'The Black Cleaver', '+55 Attack Damage +30% Attack Speed  UNIQUE Passive: Your basic attacks reduce your target''s Armor by 15 for 5 seconds (effect stacks up to 3 times).');
insert into item_information values (3072, 'The Bloodthirster', '+60 Attack Damage +15% Life Steal  Passive: Gain bonus +1 Attack Damage and +0.25% Life Steal per kill. Bonuses cap at +40 Attack Damage and +10% Life Steal. Bonuses are lost upon death.');
insert into item_information values (3075, 'Thornmail', '+100 Armor  UNIQUE Passive: On being hit by basic attacks, returns 30% of damage taken as magic damage.');
insert into item_information values (3077, 'Tiamat', '+50 Attack Damage +15 Health Regen per 5 seconds +5 Mana Regen per 5 seconds  Passive: Your basic attacks splash, dealing 50% area damage around the target (35% for ranged attacks).');
insert into item_information values (3078, 'Trinity Force', '+30 Attack Damage +30 Ability Power +30% Attack Speed +15% Critical Strike Chance +12% Movement Speed...');
insert into item_information values (3082, 'Warden''s Mail', '+50 Armor +20 Health Regen per 5 seconds  UNIQUE Passive: 20% chance on being hit by basic attacks to slow the attacker''s Movement and Attack Speeds by 35% for 3 seconds.');
insert into item_information values (3083, 'Warmog''s Armor', '+920 Health +30 Health Regen per 5 seconds  Passive: Minion kills permanently grant 3.5 Health and .10...');
insert into item_information values (3086, 'Zeal', '+20% Attack Speed +10% Critical Strike Chance +8% Movement Speed');
insert into item_information values (3089, 'Rabadon''s Deathcap', '+140 Ability Power  UNIQUE Passive: Increases Ability Power by 30%');
insert into item_information values (3091, 'Wit''s End', '+40% Attack Speed +30 Magic Resist  UNIQUE Passive: Your basic attacks deal 42 bonus magic damage.  UNIQUE Passive: Your basic attacks increase your Magic Resist by 5 for 5 seconds (effect stacks up to 4 times).');
insert into item_information values (3093, 'Avarice Blade', '+12% Critical Strike Chance  UNIQUE Passive: Gain an additional 5 Gold every 10 seconds.');
insert into item_information values (3096, 'Philosopher''s Stone', '+18 Health Regen per 5 seconds +8 Mana Regen per 5 seconds  UNIQUE Passive: Gain an additional 5 Gold every 10 seconds.');
insert into item_information values (3097, 'Emblem of Valor', '+25 Armor  UNIQUE Aura: Nearby allied Champions gain 10 Health Regen per 5 seconds.');
insert into item_information values (3098, 'Kage''s Lucky Pick', '+25 Ability Power UNIQUE Passive: Gain an additional 5 Gold every 10 seconds.');
insert into item_information values (3099, 'Soul Shroud', '+520 Health  UNIQUE Aura: Nearby allied champions gain 10% Cooldown Reduction and 12 Mana Regen per 5 seconds.');
insert into item_information values (3100, 'Lich Bane', '+350 Mana +80 Ability Power +30 Magic Resist +7% Movement Speed  UNIQUE Passive: After using an ability,...');
insert into item_information values (3101, 'Stinger', '+40% Attack Speed  UNIQUE Passive: +10% Cooldown Reduction');
insert into item_information values (3102, 'Banshee''s Veil', '+375 Health +375 Mana +50 Magic Resist  UNIQUE Passive: Gain a spell shield that blocks the next incoming enemy ability (45 second cooldown).');
insert into item_information values (3105, 'Aegis of the Legion', '+270 Health +18 Armor +24 Magic Resist  UNIQUE Aura: Nearby allied champions gain 12 Armor, 15 Magic Resist, and 8 Attack Damage.');
insert into item_information values (3106, 'Madred''s Razors', '+15 Attack Damage +23 Armor  UNIQUE Passive: Your basic attacks against minions and monsters have a 20% chance to deal 300 bonus magic damage.');
insert into item_information values (3108, 'Fiendish Codex', '+30 Ability Power +7 Mana Regen per 5 seconds  UNIQUE Passive: +10% Cooldown Reduction');
insert into item_information values (3109, 'Force of Nature', '+76 Magic Resist +40 Health Regen per 5 seconds +8% Movement Speed  UNIQUE Passive: Restores 0.35% of your maximum Health every second.');
insert into item_information values (3110, 'Frozen Heart', '+99 Armor +500 Mana  UNIQUE Passive: +20% Cooldown Reduction  UNIQUE Aura: Reduces the Attack Speed of nearby enemies by 20%.');
insert into item_information values (3111, 'Mercury''s Treads', '+25 Magic Resist  UNIQUE Passive: Enhanced Movement 2 (does not stack with other Boots)  UNIQUE Passive:...');
insert into item_information values (3114, 'Malady', '+25 Ability Power +50% Attack Speed  UNIQUE Passive: Your basic attacks deal 20 bonus magic damage and reduce the target''s Magic Resist by 6 for 8 seconds (effect stacks up to 4 times).');
insert into item_information values (3115, 'Nashor''s Tooth', '+50% Attack Speed +65 Ability Power +10 Mana Regen per 5 seconds  UNIQUE Passive: +25% Cooldown Reduction');
insert into item_information values (3116, 'Rylai''s Crystal Scepter', '+500 Health +80 Ability Power  UNIQUE Passive: Dealing spell damage slows the target''s Movement Speed by 35% for 1.5 seconds (15% for multi-target and damage-over-time spells).');
insert into item_information values (3117, 'Boots of Mobility', 'UNIQUE Passive: Enhanced Movement 2, increases to Enhanced Movement 5 when out of combat for 5 seconds (does not stack with other Boots).');
insert into item_information values (3123, 'Executioner''s Calling', '+18% Life Steal +15% Critical Strike Chance  UNIQUE Passive: Your basic attacks apply a mark to the target...');
insert into item_information values (3124, 'Guinsoo''s Rageblade', '+35 Attack Damage +45 Ability Power  UNIQUE Passive: On basic attack or ability use, increases your Attack Speed by 4% and Ability Power by 6 for 5 seconds (effect stacks up to 8 times).');
insert into item_information values (3126, 'Madred''s Bloodrazor', '+40 Attack Damage +40% Attack Speed +25 Armor  UNIQUE Passive: Your basic attacks deal bonus magic damage equal to 4% of the target''s maximum Health.');
insert into item_information values (3128, 'Deathfire Grasp', '+60 Ability Power +10 Mana Regen per 5 seconds  UNIQUE Passive: +15% Cooldown Reduction  UNIQUE Active:...');
insert into item_information values (3132, 'Heart of Gold', '+250 Health  UNIQUE Passive: Gain an additional 5 Gold every 10 seconds.');
insert into item_information values (3134, 'The Brutalizer', '+25 Attack Damage  UNIQUE Passive: +10% Cooldown Reduction  UNIQUE Passive: +15 Armor Penetration');
insert into item_information values (3135, 'Void Staff', '+70 Ability Power  UNIQUE Passive: +40% Magic Penetration');
insert into item_information values (3136, 'Haunting Guise', '+25 Ability Power +200 Health  UNIQUE Passive: +20 Magic Penetration');
insert into item_information values (3138, 'Leviathan', '+180 Health  UNIQUE Passive: Your champion gains 32 Health per stack, receiving 2 stacks for a kill or...');
insert into item_information values (3140, 'Quicksilver Sash', '+56 Magic Resist  UNIQUE Active: Removes all debuffs from your champion (90 second cooldown).');
insert into item_information values (3141, 'Sword of the Occult', '+10 Attack Damage UNIQUE Passive: Your champion gains 5 Attack Damage per stack, receiving 2 stacks for...');
insert into item_information values (3142, 'Youmuu''s Ghostblade', '+30 Attack Damage +15% Critical Strike Chance  UNIQUE Passive: +15% Cooldown Reduction  UNIQUE Passive:...');
insert into item_information values (3143, 'Randuin''s Omen', '+350 Health +75 Armor +25 Health Regen per 5 seconds  UNIQUE Passive: +5% Cooldown Reduction  UNIQUE...');
insert into item_information values (3144, 'Bilgewater Cutlass', '+35 Attack Damage +15% Life Steal  UNIQUE Active: Deals 150 magic damage and slows the target champion''s Movement Speed by 50% for 3 seconds (60 second cooldown).');
insert into item_information values (3145, 'Hextech Revolver', '+40 Ability Power  UNIQUE Passive: +12% Spell Vamp');
insert into item_information values (3146, 'Hextech Gunblade', '+40 Attack Damage +70 Ability Power +15% Life Steal  UNIQUE Passive: +20% Spell Vamp  UNIQUE Active: Deals 300 magic damage and slows the target champion''s Movement Speed by 50% for 3 seconds (60 second cooldown).');
insert into item_information values (3152, 'Will of the Ancients', '+50 Ability Power  UNIQUE Aura: Grants nearby allied champions 30 Ability Power and 20% Spell Vamp');
insert into item_information values (3154, 'Wriggle''s Lantern', '+23 Attack Damage +30 Armor +15% Life Steal  UNIQUE Passive: Your basic attacks against minions and monsters...');
insert into item_information values (3155, 'Hexdrinker', '+25 Attack Damage +30 Magic Resist  UNIQUE Passive: If you would take magic damage that would leave you at less than 30% Health, you first gain a shield that absorbs 250 magic damage for 3 seconds (60 second cooldown).');
insert into item_information values (3156, 'Maw of Malmortius', '+55 Attack Damage +36 Magic Resist  UNIQUE Passive: If you would take magic damage that would leave you at less than 30% Health, you first gain a shield that absorbs 400 magic damage for 5 seconds (60 second cooldown). UNIQUE Passive: +1 Attack Damage for every 2.5% of your Maximum Health that is missing.');
insert into item_information values (3157, 'Zhonya''s Hourglass', '+100 Ability Power +50 Armor  UNIQUE Active: Places your champion into Stasis for 2 seconds, rendering you invulnerable and untargetable but unable to take any action (90 second cooldown).');
insert into item_information values (3158, 'Ionian Boots of Lucidity', 'UNIQUE Passive: +15% Cooldown Reduction  UNIQUE Passive: Enhanced Movement 2 (does not stack with other Boots)');
insert into item_information values (3165, 'Morello''s Evil Tome', '+75 Ability Power +12 Mana Regen per 5 seconds  UNIQUE Passive: +20% Cooldown Reduction');
insert into item_information values (3170, 'Moonflair Spellblade', '+50 Ability Power  UNIQUE Passive: +35 Tenacity (Tenacity reduces the duration of stuns, slows, taunts, fears, silences, blinds and immobilizes. Does not stack with other Tenacity items.)');
insert into item_information values (3172, 'Cloak and Dagger', '+20% Attack Speed +20% Critical Strike Chance  UNIQUE Passive: +35 Tenacity (Tenacity reduces the duration of stuns, slows, taunts, fears, silences, blinds and immobilizes. Does not stack with other Tenacity items.)');
insert into item_information values (3173, 'Eleisa''s Miracle', '+25 Health Regen per 5 seconds +20 Mana Regen per 5 seconds  UNIQUE Passive: +35 Tenacity (Tenacity reduces...');
insert into item_information values (3178, 'Ionic Spark', '+50% Attack Speed +250 Health  UNIQUE Passive: Every fourth basic attack unleashes a chain lightning, dealing 110 magic damage to up to 4 targets.');
insert into item_information values (3180, 'Odyn''s Veil', '+350 Health +350 Mana +50 Magic Resist  UNIQUE Passive: Reduces and stores 10% of the magic damage dealt...');
insert into item_information values (3181, 'Sanguine Blade', '+60 Attack Damage +15% Life Steal  UNIQUE Passive: Your basic attacks grant 5 Attack Damage and 1% Life Steal for 4 seconds (effect stacks up to 7 times).');
insert into item_information values (3184, 'Entropy', '+275 Health +70 Attack Damage UNIQUE Passive: Your basic attacks have a 25% chance to reduce your target''s...');
insert into item_information values (3185, 'The Lightbringer', '+50% Attack Speed +20 Attack Damage  UNIQUE Passive: Your basic attacks grant vision of your target for 5 seconds.');
insert into item_information values (3186, 'Kitae''s Bloodrazor', '+30 Attack Damage +40% Attack Speed  UNIQUE Passive: Your basic attacks deal magic damage equal to 2.5% of the target''s maximum Health.');
insert into item_information values (3187, 'Hextech Sweeper', '+40 Ability Power +300 Health  UNIQUE Passive: +10% Cooldown Reduction  UNIQUE Passive: Dealing spell...');
insert into item_information values (3190, 'Locket of the Iron Solari', '+300 Health +35 Armor UNIQUE Aura: Nearby allied Champions gain 15 Health Regen per 5 seconds. UNIQUE Active: Shield yourself and nearby allies for 5 seconds, absorbing up to 50 (+10 per level) damage (60 second cooldown).');
insert into item_information values (3196, 'Augment: Power', '+3 Ability Power per level +220 Health +6 Health Regen per 5 seconds  Ability Augment: Power Transfer increases Viktor''s Movement Speed by 30% for 3 seconds.');
insert into item_information values (3197, 'Augment: Gravity', '+3 Ability Power per level +200 Mana +10% Cooldown Reduction +5 Mana Regen per 5 seconds  Ability Augment: Gravity Field has an additional 30% cast range.');
insert into item_information values (3198, 'Augment: Death', '+3 Ability Power per level +45 Ability Power  Augment Ability: Death Ray sets fire to enemies, dealing 30% additional magic damage over 4 seconds.');
insert into item_information values (3200, 'The Hex Core', '+3 Ability Power per level. This item can be upgraded into one of three augments that enhance Viktor''s basic abilities. Click the item in the store to discover its upgrades.');

end;